/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package secondquestion;

/**
 *
 * @author sid
 */
public class taFrame extends javax.swing.JFrame {

    /**
     * Creates new form taFrame
     */
    dataBase db = MainFrame.db;
    public taFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rollNumberBox = new javax.swing.JTextField();
        attendenceBox = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        totalClassesBox = new javax.swing.JTextField();
        approvedLeavesBox = new javax.swing.JTextField();
        assignmentBox1 = new javax.swing.JTextField();
        midMarksBox1 = new javax.swing.JTextField();
        midMarksBox2 = new javax.swing.JTextField();
        assignmentBox2 = new javax.swing.JTextField();
        assignmentBox3 = new javax.swing.JTextField();
        assignmentBox4 = new javax.swing.JTextField();
        assignmentBox5 = new javax.swing.JTextField();
        endMarksBox1 = new javax.swing.JTextField();
        endMarksBox2 = new javax.swing.JTextField();
        addButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Add Marks");

        jLabel2.setText("RollNumber  :");

        jLabel3.setText("Attendence :");

        jLabel4.setText("Approved Leaves :");

        jLabel5.setText("Marks in Assignments : ");

        jLabel6.setText("Marks in mid sems :");

        jLabel7.setText("Marks in end sems :");

        rollNumberBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rollNumberBoxMouseClicked(evt);
            }
        });

        attendenceBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                attendenceBoxMouseClicked(evt);
            }
        });
        attendenceBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attendenceBoxActionPerformed(evt);
            }
        });

        jLabel8.setText("Total Number of classes :");

        totalClassesBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                totalClassesBoxMouseClicked(evt);
            }
        });

        approvedLeavesBox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                approvedLeavesBoxMouseClicked(evt);
            }
        });

        assignmentBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                assignmentBox1MouseClicked(evt);
            }
        });
        assignmentBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignmentBox1ActionPerformed(evt);
            }
        });

        midMarksBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                midMarksBox1MouseClicked(evt);
            }
        });

        assignmentBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                assignmentBox2MouseClicked(evt);
            }
        });
        assignmentBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assignmentBox2ActionPerformed(evt);
            }
        });

        assignmentBox3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                assignmentBox3MouseClicked(evt);
            }
        });

        assignmentBox4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                assignmentBox4MouseClicked(evt);
            }
        });

        assignmentBox5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                assignmentBox5MouseClicked(evt);
            }
        });

        addButton.setText("Add");
        addButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButtonMouseClicked(evt);
            }
        });
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(295, 295, 295)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel8))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(52, 52, 52)))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rollNumberBox)
                                    .addComponent(attendenceBox)
                                    .addComponent(totalClassesBox)
                                    .addComponent(approvedLeavesBox)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(assignmentBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(assignmentBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(assignmentBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(assignmentBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(assignmentBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(midMarksBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(midMarksBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(endMarksBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(endMarksBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(rollNumberBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(attendenceBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(totalClassesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(approvedLeavesBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(assignmentBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assignmentBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assignmentBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assignmentBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(assignmentBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(midMarksBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(midMarksBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(endMarksBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(endMarksBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(addButton)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rollNumberBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rollNumberBoxMouseClicked
        // TODO add your handling code here:
        addButton.setText("Add");
        rollNumberBox.setText("");
    }//GEN-LAST:event_rollNumberBoxMouseClicked

    private void attendenceBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attendenceBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attendenceBoxActionPerformed

    private void assignmentBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignmentBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assignmentBox1ActionPerformed

    private void assignmentBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assignmentBox1MouseClicked
        // TODO add your handling code here:
        assignmentBox1.setText("");
    }//GEN-LAST:event_assignmentBox1MouseClicked

    private void assignmentBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assignmentBox2MouseClicked
        // TODO add your handling code here:
        assignmentBox2.setText("");
    }//GEN-LAST:event_assignmentBox2MouseClicked

    private void assignmentBox3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assignmentBox3MouseClicked
        // TODO add your handling code here:
        assignmentBox3.setText("");
    }//GEN-LAST:event_assignmentBox3MouseClicked

    private void assignmentBox4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assignmentBox4MouseClicked
        // TODO add your handling code here:
        assignmentBox4.setText("");
    }//GEN-LAST:event_assignmentBox4MouseClicked

    private void assignmentBox5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assignmentBox5MouseClicked
        // TODO add your handling code here:
        assignmentBox5.setText("");
    }//GEN-LAST:event_assignmentBox5MouseClicked

    private void attendenceBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendenceBoxMouseClicked
        // TODO add your handling code here:
        attendenceBox.setText("");
    }//GEN-LAST:event_attendenceBoxMouseClicked

    private void totalClassesBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_totalClassesBoxMouseClicked
        // TODO add your handling code here:
        totalClassesBox.setText("");
    }//GEN-LAST:event_totalClassesBoxMouseClicked

    private void approvedLeavesBoxMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_approvedLeavesBoxMouseClicked
        // TODO add your handling code here:
        approvedLeavesBox.setText("");
    }//GEN-LAST:event_approvedLeavesBoxMouseClicked

    private void midMarksBox1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_midMarksBox1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_midMarksBox1MouseClicked

    private void addButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButtonMouseClicked
        // TODO add your handling co
    }//GEN-LAST:event_addButtonMouseClicked

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        studentParameters temp = new studentParameters();
        temp.set_rollNumber(rollNumberBox.getText());
        
        int p = Integer.parseInt(attendenceBox.getText());
        int q = Integer.parseInt(totalClassesBox.getText());
        temp.set_attendence(p,q);
        
        p = Integer.parseInt(approvedLeavesBox.getText());
        temp.set_approvedLeaves(p);
        
        int arr[] = new int[5];
        arr[0] = Integer.parseInt(assignmentBox1.getText());
        arr[1] = Integer.parseInt(assignmentBox2.getText());
        arr[2] = Integer.parseInt(assignmentBox3.getText());
        arr[3] = Integer.parseInt(assignmentBox4.getText());
        arr[4] = Integer.parseInt(assignmentBox5.getText());
        
        temp.set_assignmentMarks(arr);
        
        arr[0] = Integer.parseInt(midMarksBox1.getText());
        arr[1] = Integer.parseInt(midMarksBox2.getText());
        temp.set_midsemMarks(arr);
        
        arr[0] = Integer.parseInt(endMarksBox1.getText());
        arr[1] = Integer.parseInt(endMarksBox2.getText());
        temp.set_endsemMarks(arr);
        
        db.addStudentParameter(temp);
        
        addButton.setText("Added!");
    }//GEN-LAST:event_addButtonActionPerformed

    private void assignmentBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignmentBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_assignmentBox2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(taFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(taFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(taFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(taFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new taFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JTextField approvedLeavesBox;
    private javax.swing.JTextField assignmentBox1;
    private javax.swing.JTextField assignmentBox2;
    private javax.swing.JTextField assignmentBox3;
    private javax.swing.JTextField assignmentBox4;
    private javax.swing.JTextField assignmentBox5;
    private javax.swing.JTextField attendenceBox;
    private javax.swing.JTextField endMarksBox1;
    private javax.swing.JTextField endMarksBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField midMarksBox1;
    private javax.swing.JTextField midMarksBox2;
    private javax.swing.JTextField rollNumberBox;
    private javax.swing.JTextField totalClassesBox;
    // End of variables declaration//GEN-END:variables
}
